name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public `.io` repo
        uses: actions/checkout@v4
        with:
          path: IEEE-Coogs.github.io
          ref: main

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: IEEE-Coogs/DevOps-and-frontend
          token: ${{ secrets.PAT_TOKEN }}
          path: DevOps-and-frontend
          ref: main

      - name: Copy HTML, CSS, and JS files
        run: |
          cp DevOps-and-frontend/src/html/index.html IEEE-Coogs.github.io/
          cp DevOps-and-frontend/src/css/styles.css IEEE-Coogs.github.io/public/
          cp DevOps-and-frontend/src/js/script.js IEEE-Coogs.github.io/
          

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'IEEE-Coogs.github.io'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
